name: E2E Tests

on:
  push:
  pull_request:

jobs:
  test-e2e:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install the latest version of kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/latest/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Verify kind installation
        run: kind version

      - name: Create kind cluster
        run: kind create cluster

      - name: Running Test e2e
        run: |
          go mod tidy
          make test-e2e


  chainsaw-test:
    name: Chainsaw Test
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        k8s-version: ['1.26.14', '1.27.11']
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: '1.24'
        cache: false
    - name: Create KinD clustet pur
      env:
        KIND_K8S_VERSION: ${{ matrix.k8s-version}}
        KUBECONFIG: kind-kubeconfig-${{ matrix.k8s-version }}
      run: make kind-create
    - name: Chainsaw test setup
      env:
        KIND_K8S_VERSION: ${{ matrix.k8s-version }}
        KUBECONFIG: kind-kubeconfig-${{ matrix.k8s-version }}
      run: make chainsaw-setup
    - name: Test with Chainsaw
      env:
        KIND_K8S_VERSION: ${{ matrix.k8s-version }}
        KUBECONFIG: kind-kubeconfig-${{ matrix.k8s-version }}
      run: make chainsaw-test
